Update dockerfile to version 8.8.2.0

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -1,7 +1,7 @@
 # Automatically generated Dockerfile 
-# - Build 2020-11-22 10:33
-# - Lucene/Solr version 8.7.0
-# - Mtas release 8.7.0.0 
+# - Build 2021-06-06 06:56
+# - Lucene/Solr version 8.8.2
+# - Mtas release 8.8.2.0 
 #
 
 FROM ubuntu:16.04
@@ -15,7 +15,7 @@ WORKDIR "/root"
 
 RUN mkdir lib 
 
-ADD https://github.com/textexploration/mtas/releases/download/v8.7.0.0/mtas-8.7.0.0.jar /root/lib/
+ADD https://github.com/textexploration/mtas/releases/download/v8.8.2.0/mtas-8.8.2.0.jar /root/lib/
 
 RUN apt-get update && apt-get install -y locales lsof software-properties-common python-software-properties apache2 curl subversion && \
     locale-gen en_US.UTF-8 en_US && update-locale LANG=en_US.UTF-8 LANGUAGE=en_US:en
@@ -40,17 +40,17 @@ RUN add-apt-repository -y ppa:webupd8team/java && \
     apt-get install -y oracle-java8-installer && \
     rm -rf /var/lib/apt/lists/*
 
-RUN solrurl=$(curl -s 'http://www.apache.org/dyn/closer.lua/lucene/solr/8.7.0/solr-8.7.0.tgz' |   grep -o '<strong>[^<]*</strong>' |   sed 's/<[^>]*>//g' |   head -1) && \
+RUN solrurl=$(curl -s 'http://www.apache.org/dyn/closer.lua/lucene/solr/8.8.2/solr-8.8.2.tgz' |   grep -o '<strong>[^<]*</strong>' |   sed 's/<[^>]*>//g' |   head -1) && \
     if echo "$solrurl" | grep -q '^.*[^ ].*$'; then \
-      curl -f -o /root/solr-8.7.0.tgz -O $solrurl || true; \
+      curl -f -o /root/solr-8.8.2.tgz -O $solrurl || true; \
     fi && \
-    if [ ! -f /root/solr-8.7.0.tgz ]; then \
-      echo "Solr 8.7.0 not found in mirror, falling back to apache archive"; \ 
-      solrurl="http://archive.apache.org/dist/lucene/solr/8.7.0/solr-8.7.0.tgz"; \
-      curl -f -o /root/solr-8.7.0.tgz -O $solrurl; \ 
+    if [ ! -f /root/solr-8.8.2.tgz ]; then \
+      echo "Solr 8.8.2 not found in mirror, falling back to apache archive"; \ 
+      solrurl="http://archive.apache.org/dist/lucene/solr/8.8.2/solr-8.8.2.tgz"; \
+      curl -f -o /root/solr-8.8.2.tgz -O $solrurl; \ 
     fi && \    
-    tar xzf solr-8.7.0.tgz solr-8.7.0/bin/install_solr_service.sh --strip-components=2 && \
-    bash ./install_solr_service.sh solr-8.7.0.tgz && rm install_solr_service.sh && rm -rf solr-8.7.0.tgz
+    tar xzf solr-8.8.2.tgz solr-8.8.2/bin/install_solr_service.sh --strip-components=2 && \
+    bash ./install_solr_service.sh solr-8.8.2.tgz && rm install_solr_service.sh && rm -rf solr-8.8.2.tgz
     
 RUN service apache2 stop && \
     echo "ServerName localhost" | tee /etc/apache2/conf-available/fqdn.conf && \
@@ -74,9 +74,9 @@ RUN service apache2 stop && \
     chmod -R 755 /var/www/html && \
     printf "echo\n" >> /start.sh && \
     printf "echo \"================ Mtas -- Multi Tier Annotation Search =================\"\n" >> /start.sh && \
-    printf "echo \"  Timestamp 2020-11-22 10:33\"\n" >> /start.sh && \
-    printf "echo \"  Lucene/Solr version 8.7.0\"\n" >> /start.sh && \
-    printf "echo \"  Mtas release 8.7.0.0\"\n" >> /start.sh && \
+    printf "echo \"  Timestamp 2021-06-06 06:56\"\n" >> /start.sh && \
+    printf "echo \"  Lucene/Solr version 8.8.2\"\n" >> /start.sh && \
+    printf "echo \"  Mtas release 8.8.2.0\"\n" >> /start.sh && \
     printf "echo \"  See https://textexploration.github.io/mtas/ for more information\"\n" >> /start.sh && \
     printf "echo \"=======================================================================\"\n" >> /start.sh && \
     printf "echo\n" >> /start.sh && \
@@ -85,7 +85,7 @@ RUN service apache2 stop && \
     mkdir demo1 && mkdir demo1/lib && mkdir demo1/conf && \
     echo "name=demo1" > demo1/core.properties && \
     cp lib/commons-math3-3.6.1.jar demo1/lib/ && \
-    cp lib/mtas-8.7.0.0.jar demo1/lib/ && \
+    cp lib/mtas-8.8.2.0.jar demo1/lib/ && \
     cp data/solrconfig.xml demo1/conf/ && \
     cp data/schemaBasic.xml demo1/conf/schema.xml && \
     cp -r data/mtas demo1/conf/ && cp data/mtas.xml demo1/conf/ && \
